CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS currencies (
    id SMALLSERIAL PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS balances (
    balance_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    currency_id SMALLINT NOT NULL REFERENCES currencies (id) ON DELETE RESTRICT,
    available NUMERIC(20, 8) NOT NULL CHECK (available >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, currency_id)
);

CREATE TABLE IF NOT EXISTS withdrawals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    balance_id BIGINT NOT NULL REFERENCES balances (balance_id) ON DELETE RESTRICT,
    amount NUMERIC(20, 8) NOT NULL CHECK (amount > 0),
    destination TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
    balance_id BIGINT NOT NULL REFERENCES balances (balance_id) ON DELETE RESTRICT,
    idempotency_key TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    withdrawal_id UUID REFERENCES withdrawals (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (balance_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_balance_created_at
    ON withdrawals (balance_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_idempotency_keys_created_at
    ON idempotency_keys (created_at DESC);

INSERT INTO currencies (id, code, name)
VALUES
    (1, 'USDT', 'Tether')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, username, email, password_hash, role)
VALUES
    (1, 'user_1', 'user1@example.com', '$2a$06$ZH6L4rx5op4wQ7lo3N9dfemcb1IRd8AVM4Ut.vhJWl3PYmFuZFUky', 'user'),
    (2, 'user_2', 'user2@example.com', '$2a$06$ZH6L4rx5op4wQ7lo3N9dfemcb1IRd8AVM4Ut.vhJWl3PYmFuZFUky', 'user'),
    (3, 'user_3', 'user3@example.com', '$2a$06$ZH6L4rx5op4wQ7lo3N9dfemcb1IRd8AVM4Ut.vhJWl3PYmFuZFUky', 'user'),
    (4, 'admin',  'admin@example.com', '$2a$06$ZH6L4rx5op4wQ7lo3N9dfemcb1IRd8AVM4Ut.vhJWl3PYmFuZFUky', 'admin')
ON CONFLICT (id) DO NOTHING;

INSERT INTO balances (balance_id, user_id, currency_id, available, updated_at)
VALUES
    (1, 1, 1, 1000.00000000, now()),
    (2, 2, 1, 15.00000000, now()),
    (3, 3, 1, 250.50000000, now()),
    (4, 4, 1, 0.00000000, now())
ON CONFLICT (balance_id) DO NOTHING;

INSERT INTO withdrawals (id, balance_id, amount, destination)
VALUES
    ('11111111-1111-1111-1111-111111111111', 1, 50.00000000, 'wallet_test_1'),
    ('22222222-2222-2222-2222-222222222222', 2, 10.00000000, 'wallet_test_2')
ON CONFLICT (id) DO NOTHING;

INSERT INTO idempotency_keys (balance_id, idempotency_key, payload_hash, withdrawal_id)
VALUES
    (1, 'idem_test_success_1', 'hash_test_success_1', '11111111-1111-1111-1111-111111111111'),
    (2, 'idem_test_in_progress_1', 'hash_test_in_progress_1', NULL)
ON CONFLICT (balance_id, idempotency_key) DO NOTHING;
