{
 "title": "Metrics v1.1.0",
 "description": "Golang Application Runtime metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, kubernetes_namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(go_goroutines{kubernetes_namespace=\"$namespace\"}, kubernetes_pod_name)"
   },
   { "name": "code", "query": { "query": "label_values(status)" } },
   { "name": "method", "query": { "query": "label_values(method)" } },
   { "name": "logger_method", "label": "logger method", "query": "GET, POST, PUT, DELETE" }
  ]
 },
 "panels": [
  {
   "title": "OpenTelemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS по ручкам",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"my-app\" && span.http.request.method =~ \"GET|POST|PUT|DELETE\"} | rate() by (span.http.request.method)",
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "RPS по статусу: $code и методу: $logger_method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "limit": 50,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"my-app\" && span.http.request.method = \"$logger_method\" && span.http.response.status_code = $code} | rate() by (span.http.request.method, span.http.response.status_code)",
       "spss": 3,
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "Время ответа метода $logger_method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{span.http.response.status_code=$code && span.http.request.method=\"$logger_method\"} | quantile_over_time(duration, .999, .99, .95)",
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "RPS ошибок",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{span.http.response.status_code>=400} | rate()",
       "tableType": "traces"
      }
     ]
    }
   ]
  },
  {
   "title": "Logger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS по ручкам",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 402 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(rate({app_name=\"my-app\"} | json | method!=\"\" [1m])) by (method)"
      }
     ]
    },
    {
     "title": "RPS по статусу: $code и методу: $method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 402 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(rate({app_name=\"my-app\"} | json | code = $code | method = \"$method\" [1m])) by (method, code)",
       "legendFormat": "{{method}} {{code}}"
      }
     ]
    },
    {
     "title": "Рейт ошибок",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 410 },
     "targets": [
      {
       "direction": "backward",
       "expr": "(\r\nsum(rate({app_name=\"my-app\"} | json | code != \"200\" [1m]))\r\n/\r\nsum(rate({app_name=\"my-app\"}[1m]))\r\n) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS по ручкам",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS по статусу: $code и методу: $method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total{status = \"$code\", method=\"$method\"}[1m])) by (status,method)",
       "legendFormat": "{{method}} {{status}}"
      }
     ]
    },
    {
     "title": "Время ответа для метода: $method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 347 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{method=\"$method\"}[1m])) by (le, method))",
       "legendFormat": "95p"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{method=\"$method\"}[1m])) by (le, method))",
       "legendFormat": "99p"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{method=\"$method\"}[1m])) by (le, method))",
       "legendFormat": "99.9p"
      }
     ]
    },
    {
     "title": "Рейт ошибок",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 347 },
     "targets": [
      {
       "expr": "(\r\n  sum(rate(http_server_requests_total{status !=\"200\"}[1m]))\r\n  /\r\n  sum(rate(http_server_requests_total{}[1m]))\r\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration среднее",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_sum{}[1m]) / rate(http_server_request_duration_seconds_count{}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration 50-й перцентиль (медиана)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 268 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration 90-й перцентиль",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 276 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration 95-й перцентиль",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 284 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration 99-й перцентиль",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 292 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration 99.9-й перцентиль",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 300 },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS статус $code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total{status = \"$code\"}[1m])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS по ручкам",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS ошибок",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total{status != \"200\"}[1m])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 253 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total[5m])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Процент ошибок от общего числа запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 253 },
     "targets": [
      {
       "expr": "(\r\n  sum(rate(http_server_requests_total{status !=\"200\"}[1m]))\r\n  /\r\n  sum(rate(http_server_requests_total{}[1m]))\r\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Golang",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"} - go_memstats_other_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"} - go_memstats_frees_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 230 },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 230 },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    }
   ]
  }
 ]
}